### ISSUE TITLE
可以实现前台添加任务吗？

### ISSUE THREAD

**Issue by fangjiyuan** [amisadmin/fastapi_scheduler#1]
可以实现前台添加任务吗？跪求更新。

**Comment by amisadmin** [comment]
可以实现，你可以通过继承｀SchedulerAdmin｀实现很多个性化需求。目前我个人时间精力有限，可能没办法弄的太细，如果你有好的实现欢迎提交，谢谢支持

**Comment by fangjiyuan** [comment]
感谢您的回复。
